### Importing Libraries

In [57]:
import pandas as pd
import requests

### Pull Data from OpenWeatherMap.org Using their API

The data used was gotten from OpenWeatherMap.org. The API address in the line of code below contains the API key you can get from their website. The idea is to change the value assigned to 'q' whenever you wish to specify a place to look up its weather.

A trial is done below for Alabama.

In [58]:
js_data = requests.get('http://api.openweathermap.org/data/2.5/weather?appid=0c42f7f6b53b244c78a418f4f181282a&q=alabama').json()
print(js_data)

{'coord': {'lon': -78.39, 'lat': 43.1}, 'weather': [{'id': 521, 'main': 'Rain', 'description': 'shower rain', 'icon': '09d'}, {'id': 701, 'main': 'Mist', 'description': 'mist', 'icon': '50d'}], 'base': 'stations', 'main': {'temp': 293.56, 'pressure': 1009, 'humidity': 93, 'temp_min': 291.48, 'temp_max': 295.93}, 'visibility': 11265, 'wind': {'speed': 1.5, 'deg': 210}, 'rain': {'1h': 1.02}, 'clouds': {'all': 90}, 'dt': 1565185252, 'sys': {'type': 1, 'id': 4291, 'message': 0.009, 'country': 'US', 'sunrise': 1565172618, 'sunset': 1565224106}, 'timezone': -14400, 'id': 5118380, 'name': 'Alabama', 'cod': 200}

In the JSON data returned, we see the different dictionaries and list we have. We can take those units apart and then combine them into a pandas dataframe as a neat dataset and do so for different areas / states. That is what we have done below.

First, we created a list of places we wish to curate their weather information, and then pull out all the details we wish to have in our dataset.

In [59]:
us_states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 
             'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
             'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 
            'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 
             'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
             'South Carolina', 'South Dakota', 'West Virginia', 'Tennessee', 'Texas', 'Utah', 'Vermont', 
             'Virginia', 'Washington', 'Wisconsin', 'Wyoming', 'London', 'Paris']

In [64]:
city_long = []
city_lat = []
city_weather = []
city_base = []
city_pressure = []
city_humidity = []
city_temp = []
city_temp_min = []
city_temp_max = []
city_visibility = []
city_windspeed = []
city_wind_deg = []
city_country = []
city_sunrise = []
city_sunset = []
city_timezone = []


for state in us_states:
    api_address='http://api.openweathermap.org/data/2.5/weather?appid=0c42f7f6b53b244c78a418f4f181282a&q='
    url = api_address + state
    json_data = requests.get(url).json()
    
    try:
        cty_lon = json_data['coord']['lon']
        city_long.append(cty_lon)
    except:
        city_long.append('NA')
    
    try:
        cty_lat = json_data['coord']['lat']
        city_lat.append(cty_lat)
    except:
        city_lat.append('NA')
    
    cty_we = json_data['weather'][0]
    cty_wea = cty_we['description']
    city_weather.append(cty_wea)
    print(state + '  --  ' + cty_wea)
    
    cty_base = json_data['base']
    city_base.append(cty_base)
    
    cty_press = json_data['main']['pressure']
    city_pressure.append(cty_press)
    
    cty_humid = json_data['main']['humidity']
    city_humidity.append(cty_humid)
    
    cty_temp = json_data['main']['temp']
    city_temp.append(cty_temp)
    
    cty_temp_min = json_data['main']['temp_min']
    city_temp_min.append(cty_temp_min)
    
    cty_temp_max = json_data['main']['temp_max']
    city_temp_max.append(cty_temp_max)
    
    try:
        cty_visi = json_data['visibility']
        city_visibility.append(cty_visi)
    except:
        city_visibility.append('NA')
    
    cty_speed = json_data['wind']['speed']
    city_windspeed.append(cty_speed)
    
    try:
        cty_deg = json_data['wind']['deg']
        city_wind_deg.append(cty_deg)
    except:
        city_wind_deg.append('NA')
    
    cty_country = json_data['sys']['country']
    city_country.append(cty_country)
    
    cty_srise = json_data['sys']['sunrise']
    city_sunrise.append(cty_srise)
    
    cty_sset = json_data['sys']['sunset']
    city_sunset.append(cty_sset)
    
    cty_tz = json_data['timezone']
    city_timezone.append(cty_tz)

Alabama  --  shower rain
Alaska  --  clear sky
Arizona  --  clear sky
Arkansas  --  overcast clouds
California  --  broken clouds
Colorado  --  clear sky
Connecticut  --  mist
Delaware  --  mist
Florida  --  broken clouds
Georgia  --  few clouds
Hawaii  --  mist
Idaho  --  clear sky
Illinois  --  clear sky
Indiana  --  broken clouds
Iowa  --  clear sky
Kansas  --  clear sky
Kentucky  --  clear sky
Louisiana  --  scattered clouds
Maine  --  broken clouds
Maryland  --  broken clouds
Massachusetts  --  broken clouds
Michigan  --  overcast clouds
Minnesota  --  clear sky
Mississippi  --  fog
Montana  --  clear sky
Nebraska  --  mist
Nevada  --  scattered clouds
New Hampshire  --  mist
New Jersey  --  broken clouds
New Mexico  --  haze
New York  --  fog
North Carolina  --  scattered clouds
North Dakota  --  overcast clouds
Ohio  --  clear sky
Oklahoma  --  mist
Oregon  --  clear sky
Pennsylvania  --  scattered clouds
Rhode Island  --  scattered clouds
South Carolina  --  clear sky
South Dakota  --  clear sky
West Virginia  --  broken clouds
Tennessee  --  clear sky
Texas  --  broken clouds
Utah  --  clear sky
Vermont  --  moderate rain
Virginia  --  clear sky
Washington  --  clear sky
Wisconsin  --  clear sky
Wyoming  --  few clouds
London  --  shower rain
Paris  --  overcast clouds

In [70]:
us_weather_data = pd.DataFrame({'Name of City': us_states,
                                'Latitude': city_lat,
                       'Longitude': city_long,
                       'Weather': city_weather,
                        'Base': city_base,
                        'Pressure': city_pressure,
                        'Humidity': city_humidity,
                        'Temp': city_temp,
                        'Min Temp': city_temp_min,
                        'Max Temp': city_temp_max,
                        'Visibility': city_visibility,
                        'WindSpeed': city_windspeed,
                        'Wind Degree': city_wind_deg,
                        'Country': city_country,
                        'Sunrise': city_sunrise,
                        'Sunset': city_sunset,
                        'Timezone': city_timezone
                                })
print(us_weather_data.info())
us_weather_data.head(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 17 columns):
Name of City    51 non-null object
Latitude        51 non-null float64
Longitude       51 non-null float64
Weather         51 non-null object
Base            51 non-null object
Pressure        51 non-null float64
Humidity        51 non-null int64
Temp            51 non-null float64
Min Temp        51 non-null float64
Max Temp        51 non-null float64
Visibility      51 non-null object
WindSpeed       51 non-null float64
Wind Degree     51 non-null object
Country         51 non-null object
Sunrise         51 non-null int64
Sunset          51 non-null int64
Timezone        51 non-null int64
dtypes: float64(7), int64(4), object(6)
memory usage: 6.9+ KB
None

,Name of City,Latitude,Longitude,Weather,Base,Pressure,Humidity,Temp,Min Temp,Max Temp,Visibility,WindSpeed,Wind Degree,Country,Sunrise,Sunset,Timezone
0,Alabama,43.10,-78.39,shower rain,stations,1009.00,93,293.560,291.480,295.930,11265,1.50,210,US,1565172618,1565224106,-14400
1,Alaska,-17.38,30.08,clear sky,stations,1013.54,15,302.211,302.211,302.211,NA,2.72,85.629,ZW,1565151791,1565192871,7200
2,Arizona,-28.39,-49.38,clear sky,stations,1022.96,42,299.411,299.411,299.411,NA,0.34,293.706,BR,1565171767,1565211033,-10800
3,Arkansas,37.58,-82.73,overcast clouds,stations,1014.00,78,295.000,293.710,296.150,16093,3.48,260.006,US,1565174385,1565224423,-14400
4,California,25.76,-103.38,broken clouds,stations,1018.00,50,299.150,299.150,299.150,16093,3.60,100,MX,1565180564,1565228155,-18000
5,Colorado,-22.84,-51.97,clear sky,stations,1023.20,49,299.411,299.411,299.411,NA,5.87,37.184,BR,1565171910,1565212133,-10800
6,Connecticut,41.67,-72.67,mist,stations,1011.00,88,296.850,294.820,298.710,16093,1.50,210,US,1565171445,1565222534,-14400
7,Delaware,40.30,-83.07,mist,stations,1011.00,88,294.620,292.590,296.480,16093,2.66,293.689,US,1565174126,1565224844,-14400
8,Florida,-34.10,-56.21,broken clouds,stations,1020.61,89,287.611,287.611,287.611,NA,4.56,155.834,UY,1565173952,1565212126,-10800
9,Georgia,17.96,-76.51,few clouds,stations,1014.00,62,304.150,304.150,304.150,10000,7.70,130,JM,1565174774,1565221048,-18000
10,Hawaii,20.75,-156.50,mist,stations,1015.00,83,295.830,293.710,297.150,16093,1.63,179.018,US,1565193749,1565240465,-36000
11,Idaho,35.09,-87.29,clear sky,stations,1014.00,88,296.980,295.150,298.710,16093,3.87,267.139,US,1565175768,1565225228,-18000
12,Illinois,40.00,-89.25,clear sky,stations,1013.00,83,295.490,292.590,297.590,16093,2.13,267.234,US,1565175649,1565226287,-18000
13,Indiana,40.62,-79.15,broken clouds,stations,1013.00,94,293.510,292.040,294.820,11265,3.10,240,US,1565173142,1565223946,-14400
14,Iowa,30.24,-93.01,clear sky,stations,1015.00,88,301.110,299.150,302.150,16093,1.53,263.144,US,1565177651,1565226090,-18000
15,Kansas,33.90,-87.55,clear sky,stations,1015.00,100,296.910,295.150,298.150,14484,2.99,261.683,US,1565175961,1565225160,-18000
16,Kentucky,-32.94,-60.83,clear sky,stations,1020.00,71,286.160,284.820,287.590,10000,6.20,160,AR,1565174944,1565213352,-10800
17,Louisiana,25.80,-109.06,scattered clouds,stations,1012.00,69,300.620,300.370,301.150,12874,3.10,80,MX,1565181924,1565229521,-21600
18,Maine,42.19,-76.06,broken clouds,stations,1011.00,88,293.790,292.040,295.370,16093,2.60,NA,US,1565172187,1565223418,-14400
19,Maryland,-32.88,151.66,broken clouds,stations,1010.00,81,284.640,280.150,289.820,10000,1.98,317.761,AU,1565123972,1565162336,36000
20,Massachusetts,42.37,-71.11,broken clouds,stations,1011.00,69,297.600,296.150,299.260,16093,4.10,230,US,1565170973,1565222257,-14400
21,Michigan,48.02,-98.12,overcast clouds,stations,1013.00,82,290.160,289.150,291.150,16093,4.60,350,US,1565176577,1565229617,-18000
22,Minnesota,40.66,-122.49,clear sky,stations,1016.00,54,288.330,284.260,292.590,16093,1.50,270,US,1565183546,1565234345,-25200
23,Mississippi,-39.45,-73.22,fog,stations,1031.00,100,276.150,276.150,276.150,200,2.15,30.135,CL,1565178618,1565215625,-14400
24,Montana,43.41,23.22,clear sky,stations,1013.12,31,304.711,304.711,304.711,NA,2.14,118.942,BG,1565148168,1565199787,10800
25,Nebraska,39.06,-85.46,mist,stations,1013.00,100,294.800,293.150,296.480,3219,2.36,313.199,US,1565174859,1565225259,-14400
26,Nevada,42.02,-93.45,scattered clouds,stations,1012.00,88,294.570,292.150,296.480,16093,3.10,220,US,1565176388,1565227565,-18000
27,New Hampshire,40.56,-83.95,mist,stations,1012.00,89,295.010,293.710,296.480,16093,1.50,310,US,1565174303,1565225090,-14400
28,New Jersey,40.17,-74.50,broken clouds,stations,1010.00,78,299.160,297.040,301.150,16093,3.10,180,US,1565172085,1565222772,-14400
29,New Mexico,39.60,-76.95,haze,stations,1011.00,74,298.780,296.480,301.480,16093,3.10,270,US,1565172747,1565223286,-14400
30,New York,40.73,-73.99,fog,stations,1011.00,78,298.370,296.480,299.820,16093,4.21,187.13,US,1565171889,1565222724,-14400
31,North Carolina,35.50,-80.00,scattered clouds,stations,1014.00,83,298.730,297.150,300.370,16093,2.10,210,US,1565173971,1565223526,-14400
32,North Dakota,47.50,-100.00,overcast clouds,stations,1014.00,87,288.910,287.590,289.820,16093,5.10,340,US,1565177119,1565229977,-18000
33,Ohio,41.56,-89.46,clear sky,stations,1012.00,83,295.040,293.150,296.480,16093,2.62,269.934,US,1565175493,1565226545,-18000
34,Oklahoma,40.58,-79.57,mist,stations,1012.00,88,293.640,292.040,295.370,9656,3.10,230,US,1565173249,1565224042,-14400
35,Oregon,42.01,-89.33,clear sky,stations,1012.00,73,295.130,293.150,297.040,16093,2.96,260.009,US,1565175400,1565226575,-18000
36,Pennsylvania,50.74,-3.52,scattered clouds,stations,1008.00,60,293.610,290.930,295.930,10000,5.10,250,GB,1565153341,1565207448,3600
37,Rhode Island,31.82,-96.23,scattered clouds,stations,1014.00,94,300.150,299.150,301.480,16093,3.60,200,US,1565178264,1565227022,-18000
38,South Carolina,34.00,-81.00,clear sky,stations,1014.00,83,299.990,298.150,302.590,16093,2.10,220,US,1565174377,1565223599,-14400
39,South Dakota,44.50,-100.25,clear sky,stations,1012.00,88,292.280,291.150,293.150,16093,1.50,360,US,1565177662,1565229554,-18000
40,West Virginia,47.52,-92.57,broken clouds,stations,1008.00,93,291.130,290.370,291.480,16093,2.10,290,US,1565175330,1565228200,-18000
41,Tennessee,40.41,-90.84,clear sky,stations,1013.00,88,295.210,294.150,296.480,11265,1.97,246.63,US,1565175978,1565226722,-18000
42,Texas,-28.86,151.17,broken clouds,stations,1013.16,86,283.211,283.211,283.211,NA,1.32,99.748,AU,1565123703,1565162840,36000
43,Utah,40.98,-90.49,clear sky,stations,1013.00,88,294.980,293.710,297.040,16093,2.27,257.736,US,1565175818,1565226714,-18000
44,Vermont,-37.84,145.20,moderate rain,stations,1005.00,100,281.920,280.370,283.710,9000,4.38,352.357,AU,1565126050,1565163358,36000
45,Virginia,39.95,-90.21,clear sky,stations,1013.00,83,295.580,293.710,298.150,16093,1.47,256.53,US,1565175886,1565226511,-18000
46,Washington,38.90,-77.04,clear sky,stations,1010.00,83,299.360,297.040,301.480,16093,2.10,250,US,1565172857,1565223220,-14400
47,Wisconsin,44.50,-90.00,clear sky,stations,1010.00,82,293.710,291.480,295.370,16093,1.50,230,US,1565175200,1565227097,-18000
48,Wyoming,42.91,-85.71,few clouds,stations,1011.00,78,294.240,292.040,295.930,16093,2.61,247.421,US,1565174404,1565225834,-14400
49,London,51.51,-0.13,shower rain,stations,1007.00,77,294.500,292.040,297.040,10000,5.70,290,GB,1565152370,1565206792,3600

In [67]:
us_weather_data.shape
us_weather_data.columns

Index(['Name of City', 'Latitude', 'Longitude', 'Weather', 'Base', 'Pressure',
       'Humidity', 'Temp', 'Min Temp', 'Max Temp', 'Visibility', 'WindSpeed',
       'Wind Degree', 'Country', 'Sunrise', 'Sunset', 'Timezone'],
      dtype='object')

In [ ]:
# The Data is already in readable format; so we move on to the next section.

### Data Transformation

The column "Base" has only one entry for all cities, and the column "visibility" has many NA values; 
so they are redundant and would be dropped.

In [73]:
us_weather_data1=us_weather_data.drop([ 'Base', 'Visibility'], axis=1)
us_weather_data1.head(3)

,Name of City,Latitude,Longitude,Weather,Pressure,Humidity,Temp,Min Temp,Max Temp,WindSpeed,Wind Degree,Country,Sunrise,Sunset,Timezone
0,Alabama,43.10,-78.39,shower rain,1009.00,93,293.560,291.480,295.930,1.50,210,US,1565172618,1565224106,-14400
1,Alaska,-17.38,30.08,clear sky,1013.54,15,302.211,302.211,302.211,2.72,85.629,ZW,1565151791,1565192871,7200
2,Arizona,-28.39,-49.38,clear sky,1022.96,42,299.411,299.411,299.411,0.34,293.706,BR,1565171767,1565211033,-10800

We would fill out the NA values in Wind Degree with the average, partly because
their standard deviations are not so far apart, partly because only less than 2% of the values are missing so a wrong value has a poor chance of really altering our analysis significantly and partly because some analysis requires all cell values filled up.

In [79]:
wind_deg = []
for deg in us_weather_data1['Wind Degree']:
    try:
        wind_deg.append(float(deg))
    except:
        pass
    
def Average(lst): 
    return sum(lst) / len(lst)

print(Average(wind_deg))

227.63596

### Replacing the NA values with the Average Wind Degree

In [85]:
us_weather_data2=us_weather_data1.replace('NA', Average(wind_deg))
us_weather_data2.head()

,Name of City,Latitude,Longitude,Weather,Pressure,Humidity,Temp,Min Temp,Max Temp,WindSpeed,Wind Degree,Country,Sunrise,Sunset,Timezone
0,Alabama,43.10,-78.39,shower rain,1009.00,93,293.560,291.480,295.930,1.50,210.000,US,1565172618,1565224106,-14400
1,Alaska,-17.38,30.08,clear sky,1013.54,15,302.211,302.211,302.211,2.72,85.629,ZW,1565151791,1565192871,7200
2,Arizona,-28.39,-49.38,clear sky,1022.96,42,299.411,299.411,299.411,0.34,293.706,BR,1565171767,1565211033,-10800
3,Arkansas,37.58,-82.73,overcast clouds,1014.00,78,295.000,293.710,296.150,3.48,260.006,US,1565174385,1565224423,-14400
4,California,25.76,-103.38,broken clouds,1018.00,50,299.150,299.150,299.150,3.60,100.000,MX,1565180564,1565228155,-18000

In [86]:
us_weather_data2.isna().sum()

Name of City    0
Latitude        0
Longitude       0
Weather         0
Pressure        0
Humidity        0
Temp            0
Min Temp        0
Max Temp        0
WindSpeed       0
Wind Degree     0
Country         0
Sunrise         0
Sunset          0
Timezone        0
dtype: int64

The dataset has no missing values. We would have dropped them if it did, depending on how many of them are present.

In [89]:
us_weather_data2.shape

(51, 15)

### Handling Duplicates

In [87]:
us_weather_nodupes=us_weather_data2.drop_duplicates()
us_weather_nodupes.shape

(51, 15)

There were no duplicates in the dataset. In fact, the dataset is now nicely formatted and is ready for analysis!